version: '3.4'

services:
  peopleandorganizations.consoleapp:
    image: ${DOCKER_REGISTRY-}peopleandorganizationsconsoleapp
    build:
      context: .
      dockerfile: Source/PeopleAndOrganizations.ConsoleApp/Dockerfile
  peopledb:
    image: "mcr.microsoft.com/mssql/server"
    hostname: people-sql-server
    container_name: people-sql-server
    ports:
        - "14331:1433"
    environment:
        SA_PASSWORD: "qweasd!@!"
        ACCEPT_EULA: "Y"
    volumes:
       - ./data/data:/var/opt/mssql/data
       - ./data/log:/var/opt/mssql/log
       - ./data/secrets:/var/opt/mssql/secrets
  jediorder.web:
    image: ${DOCKER_REGISTRY-}jediorderweb
    build:
      context: .
      dockerfile: Source/JediOrder.Web/Dockerfile


  peopleandorganizations.webapi:
    image: ${DOCKER_REGISTRY-}peopleandorganizationswebapi
    build:
      context: .
      dockerfile: Source/PeopleAndOrganizations.WebApi/Dockerfile

