version: '3.4'

services:
  galacticsenate.consoleapp:
    image: ${DOCKER_REGISTRY-}galacticsenateconsoleapp
    build:
      context: .
      dockerfile: Source/GalacticSenate.ConsoleApp/Dockerfile
  galacticsenate.db:
    image: "mcr.microsoft.com/mssql/server"
    hostname: galacticsenate-sql-server
    container_name: galacticsenate-sql-server
    ports:
        - "14331:1433"
    environment:
        SA_PASSWORD: "qweasd!@!"
        ACCEPT_EULA: "Y"
    volumes:
       - ./data/data:/var/opt/mssql/data
       - ./data/log:/var/opt/mssql/log
       - ./data/secrets:/var/opt/mssql/secrets
  galacticsenate.webapi:
    image: ${DOCKER_REGISTRY-}galacticsenatewebapi
    build:
      context: .
      dockerfile: Source/GalacticSenate.WebApi/Dockerfile
  jediorder.web:
    image: ${DOCKER_REGISTRY-}jediorderweb
    build:
      context: .
      dockerfile: Source/JediOrder.Web/Dockerfile

